name: nexus_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0' # Usando a versão do Flutter 3.19.6

dependencies:
  flutter:
    sdk: flutter

  # --- Firebase ---
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.2
  firebase_storage: ^13.0.2

  # --- State / Utils ---
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  device_info_plus: ^12.1.0
  speech_to_text: ^7.3.0
  flutter_inappwebview: ^6.0.0
  flutter_tts: ^4.2.3
  just_audio: ^0.10.5

  # --- Networking ---
  http: ^1.2.1
  url_launcher: ^6.3.0
  crypto: ^3.0.3

  # --- Notifications ---
  flutter_local_notifications: ^19.4.2

  # --- Media / Files ---
  image_picker: ^1.1.2
  pdfx: ^2.6.0
  syncfusion_flutter_pdfviewer: ^31.1.23

  # --- UI / Graphics ---
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  vector_math: ^2.1.4
  intl: ^0.20.2

  # --- Env vars ---
  flutter_dotenv: ^6.0.0

  # --- LLM / AI ---
  google_generative_ai: ^0.4.3
  flutter_markdown: ^0.7.1
  langchain: ^0.7.9
  langchain_google: ^0.6.5+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Lua/Lua.png
    - assets/Lua/Lua-Transparente.png
    - assets/Lua/Lua-Preocupada.png
    - assets/Lua/Lua-Curiosa.png
    - assets/Lua/Lua-muito-surpresa.png
    - assets/icons/newsAI.svg
    - assets/Lua/icones-perfil/icone1.png
    - assets/Lua/icones-perfil/icone2.png
    - assets/Lua/icones-perfil/icone3.png
    - assets/Lua/icones-perfil/icone4.png
    - assets/Lua/icones-perfil/icone5.png
    - assets/Lua/icones-perfil/icone6.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700