// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1yZJ6m7eSSBJNez_5uBec9-KiiYu2M3o',
    appId: '1:480594485086:web:b703b50ef3fb42f58c39cf',
    messagingSenderId: '480594485086',
    projectId: 'sec4u-6b6f8',
    authDomain: 'sec4u-6b6f8.firebaseapp.com',
    storageBucket: 'sec4u-6b6f8.firebasestorage.app',
    measurementId: 'G-DLMGYPBCNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh5y_PpoWuvdUEN3XI9ZBq_dGqkhIpHIQ',
    appId: '1:480594485086:android:26fedecca64e684d8c39cf',
    messagingSenderId: '480594485086',
    projectId: 'sec4u-6b6f8',
    storageBucket: 'sec4u-6b6f8.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1m231rFoJgNUNjHocNUCSgWsTabQSIHM',
    appId: '1:480594485086:ios:fdf886adbd699cf08c39cf',
    messagingSenderId: '480594485086',
    projectId: 'sec4u-6b6f8',
    storageBucket: 'sec4u-6b6f8.firebasestorage.app',
    iosBundleId: 'com.sec4you.securityconnect',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1m231rFoJgNUNjHocNUCSgWsTabQSIHM',
    appId: '1:480594485086:ios:fdf886adbd699cf08c39cf',
    messagingSenderId: '480594485086',
    projectId: 'sec4u-6b6f8',
    storageBucket: 'sec4u-6b6f8.firebasestorage.app',
    iosBundleId: 'com.sec4you.securityconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1yZJ6m7eSSBJNez_5uBec9-KiiYu2M3o',
    appId: '1:480594485086:web:ffb0bca398cf947a8c39cf',
    messagingSenderId: '480594485086',
    projectId: 'sec4u-6b6f8',
    authDomain: 'sec4u-6b6f8.firebaseapp.com',
    storageBucket: 'sec4u-6b6f8.firebasestorage.app',
    measurementId: 'G-PEZTBRH2DE',
  );

}